# The Numpy array object

# NumPy Arrays

**python objects:** 

1. high-level number objects: integers, floating point
2. containers: lists (costless insertion and append), dictionaries (fast lookup)

**Numpy provides:**

1. extension package to Python for multi-dimensional arrays
2. closer to hardware (efficiency)
3. designed for scientific computation (convenience)
4. Also known as array oriented computing

In [6]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)

print(np.arange(23))

[0 1 2 3]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


**Why it is useful:** Memory-efficient container that provides fast numerical operations.

In [10]:
#python lists
L = range(1000)
%timeit [i**2 for i in L]

586 µs ± 52.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
a = np.arange(1000)
%timeit a**2

2.38 µs ± 15 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# 1. Creating arrays

** 1.1.  Manual Construction of arrays**

In [13]:
#1-D

a = np.array([0, 0, 2, 3,7,9])

a

array([0, 0, 2, 3, 7, 9])

In [0]:
#print dimensions

a.ndim

1

In [14]:
#shape

a.shape

(6,)

In [15]:
len(a)

6

In [27]:
# 2-D, 3-D....

b = np.array([[0, 1, 2], [3, 4, 5],[1,2,3,]])

b

array([[0, 1, 2],
       [3, 4, 5],
       [1, 2, 3]])

In [29]:
b.ndim

2

In [30]:
b.shape

(3, 3)

In [31]:
len(b) #returns the size of the first dimention

3

In [23]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])

c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [24]:
c.ndim

3

In [25]:
c.shape

(2, 2, 2)

** 1.2  Functions for creating arrays**

In [26]:
len(c)

2

In [0]:
#using arrange function

# arange is an array-valued version of the built-in Python range function

a = np.arange(10) # 0.... n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
b = np.arange(1, 10, 1) #start, end (exclusive), step

b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
#using linspace

a = np.linspace(0, 1, 4) #start, end, number of points

a

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [41]:
#common arrays

a = np.ones((3, 3))

a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
b = np.zeros((3, 3))

b

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [42]:
c = np.eye(6)  #Return a 2-D array with ones on the diagonal and zeros elsewhere.

c

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [43]:
d = np.eye(3, 7) #3 is number of rows, 2 is number of columns, index of diagonal start with 0

d

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.]])

In [44]:
#create array using diag function

a = np.diag([1, 2,  4]) #construct a diagonal array.

a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 4]])

In [45]:
np.diag(a)   #Extract diagonal

array([1, 2, 4])

In [48]:
#create array using random

#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a = np.random.rand(1) 

a

array([0.55563836])

In [49]:
a = np.random.randn(8)#Return a sample (or samples) from the “standard normal” distribution.  ***Gausian***

a

array([-0.32904364, -1.86094064,  2.1437041 ,  0.09725241, -0.83143722,
       -1.4784501 , -1.27922006,  0.32339617])

**Note:**
    
For random samples from N(\mu, \sigma^2), use:

sigma * np.random.randn(...) + mu



# 2. Basic DataTypes

You may have noticed that, in some instances, array elements are displayed with a **trailing dot (e.g. 2. vs 2)**. This is due to a difference in the **data-type** used:

In [52]:
a = np.arange(10000)

a.dtype

dtype('int32')

In [55]:
#You can explicitly specify which data-type you want:

a = np.arange(10, dtype='int32')
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
#The default data type is float for zeros and ones function

a = np.zeros((3, 3))

print(a)

a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

**other datatypes**

In [60]:
d = np.array([1+2j, 2+4j])   #Complex datatype

print(d.dtype)

complex128


In [59]:
b = np.array([True, False, True, False])  #Boolean datatype

print(b.dtype)

bool


In [58]:
s = np.array(['Ram', 'Robert', 'Rahim'])

s.dtype

dtype('<U6')

**Each built-in data type has a character code that uniquely identifies it.**

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

**For more details**

**https://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html**

# 3. Indexing and Slicing

**3.1 Indexing**

The items of an array can be accessed and assigned to the same way as other **Python sequences (e.g. lists)**:

In [63]:
a = np.arange(10)

print(a[1])  #indices begin at 0, like other Python sequences (and C/C++)

1


In [61]:
# For multidimensional arrays, indexes are tuples of integers:

a = np.diag([1, 2, 3])

print(a[2, 2])

3


In [0]:
a[2, 1] = 5 #assigning value

a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

**3.2 Slicing**

In [0]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a[1:8:2] # [startindex: endindex(exclusive) : step]

array([1, 3, 5, 7])

In [0]:
#we can also combine assignment and slicing:

a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [66]:
b = np.arange(5)
a[7:] = b[::-3]  #assigning

a

ValueError: could not broadcast input array from shape (2) into shape (3)

# 4. Copies and Views

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use **np.may_share_memory()** to check if two arrays share the same memory block. 

**When modifying the view, the original array is modified as well:**

In [78]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
b = a[:6:2]
b

array([0, 2, 4])

In [80]:
np.shares_memory(a, b)

True

In [81]:
b[0] = 10
b

array([10,  2,  4])

In [82]:
a  #eventhough we modified b,  it updated 'a' because both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [83]:


a = np.arange(10)

c = a[::2].copy()     #force a copy
c

array([0, 2, 4, 6, 8])

In [84]:
np.shares_memory(a, c)

False

In [0]:
c[0] = 10

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5. Fancy Indexing

NumPy arrays can be indexed with slices, but also with boolean or integer arrays **(masks)**. This method is called **fancy indexing**. It creates copies not views.

**Using Boolean Mask**

In [85]:
a = np.random.randint(0, 20, 15)
a

array([ 2,  8,  5, 16,  9, 10,  8,  8,  3,  6, 19, 17, 16,  0, 15])

In [86]:
mask = (a % 2 == 0)

In [87]:
extract_from_a = a[mask]

extract_from_a

array([ 2,  8, 16, 10,  8,  8,  6, 16,  0])

**Indexing with a mask can be very useful to assign a new value to a sub-array:**

In [88]:
a[mask] = -1
a

array([-1, -1,  5, -1,  9, -1, -1, -1,  3, -1, 19, 17, -1, -1, 15])

**Indexing with an array of integers**

In [89]:
a = np.arange(0, 100, 10)

a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [90]:
#Indexing can be done with an array of integers, where the same index is repeated several time:

a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [0]:
# New values can be assigned 

a[[9, 7]] = -200

a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])